/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.database.project;

import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JTable;

/**
 *
 * @author jpvan
 */
public class StudentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FacultyDashboard
     */
    public StudentDashboard() {
        initComponents();
        UpdateDB();
    }
    
    public void UpdateDB(){
        int q, i;
        int userID = LoginSession.UID;
        try{
             Connection myConn = MySQLConnection.getConnection();
             PreparedStatement pst = myConn.prepareStatement("SELECT students.sname, students.major, students.s_level, students.age, courses.cname, courses.cid, enrolled.exam1, enrolled.exam2, enrolled.final\n" +
            "FROM students, courses, enrolled\n" +
            "WHERE students.sid = ? AND ? = enrolled.sid AND enrolled.cid = courses.cid");
            
            pst.setInt(1, userID);
            pst.setInt(2, userID);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++){
                    columnData.add(rs.getString("sname"));
                    columnData.add(rs.getString("major"));
                    columnData.add(rs.getString("s_level"));
                    columnData.add(rs.getString("age"));
                    columnData.add(rs.getString("cname"));
                    columnData.add(rs.getString("cid"));
                    columnData.add(rs.getString("exam1"));
                    columnData.add(rs.getString("exam2"));
                    columnData.add(rs.getString("final"));
                }    
                    RecordTable.addRow(columnData);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        courseName_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentName_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        studentLevel_txt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        drop_classes = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        coursesButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        examTwo_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        studentMajor_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentAge_txt = new javax.swing.JTextField();
        examOne_txt = new javax.swing.JTextField();
        final_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        courseID_txt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        exit_button = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        backTo = new javax.swing.JButton();
        catalog_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 249, 234), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseName_txtActionPerformed(evt);
            }
        });
        jPanel4.add(courseName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 40));

        studentName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentName_txtActionPerformed(evt);
            }
        });
        jPanel4.add(studentName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Level");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 40));

        studentLevel_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLevel_txtActionPerformed(evt);
            }
        });
        jPanel4.add(studentLevel_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, 40));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Drop Class ");

        drop_classes.setText("Drop");
        drop_classes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drop_classesMouseClicked(evt);
            }
        });
        drop_classes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drop_classesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(drop_classes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(drop_classes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 280, 170));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Courses Catalog/Add Class");

        coursesButton.setText("Catalog");
        coursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(coursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18)))
                .addGap(43, 43, 43))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(coursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Age");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 80, 40));

        examTwo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examTwo_txtActionPerformed(evt);
            }
        });
        jPanel4.add(examTwo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 190, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Major");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 90, 40));

        studentMajor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMajor_txtActionPerformed(evt);
            }
        });
        jPanel4.add(studentMajor_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 190, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CID");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 70, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Exam 1");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Exam2");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Final");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 70, 40));

        studentAge_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAge_txtActionPerformed(evt);
            }
        });
        jPanel4.add(studentAge_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 190, 40));

        examOne_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examOne_txtActionPerformed(evt);
            }
        });
        jPanel4.add(examOne_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, 40));

        final_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final_txtActionPerformed(evt);
            }
        });
        jPanel4.add(final_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CName");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 40));
        jPanel4.add(courseID_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 190, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 440));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 249, 234), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Major", "Level", "Age", "Course Name", "CID", "Exam One", "Exam Two", "Final Exam"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 420));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 780, 440));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 249, 234), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit_button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit_button.setText("Logout");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        jPanel6.add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 20, 210, 60));

        printButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel6.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 210, 60));

        backTo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        backTo.setText("Go Back");
        backTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToActionPerformed(evt);
            }
        });
        jPanel6.add(backTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 60));

        catalog_Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        catalog_Button.setText("Catalog");
        catalog_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalog_ButtonActionPerformed(evt);
            }
        });
        jPanel6.add(catalog_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 210, 60));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1420, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1440, 570));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Student Information");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1400, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1440, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1436, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1440, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void courseName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseName_txtActionPerformed

    private void studentName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentName_txtActionPerformed

    private void studentLevel_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLevel_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentLevel_txtActionPerformed

    private void examTwo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examTwo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examTwo_txtActionPerformed

    private void studentMajor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMajor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMajor_txtActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:]
        MessageFormat header = new MessageFormat("Printing in Progress...");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("No printer found", e.getMessage());
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        LoginScreen loginScreen = new LoginScreen();
        Logout.logOut(this, loginScreen);
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        studentName_txt.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        studentMajor_txt.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        studentLevel_txt.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        studentAge_txt.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        courseName_txt.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        courseID_txt.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        examOne_txt.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        examTwo_txt.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
        final_txt.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
         
    }//GEN-LAST:event_jTable1MouseClicked

    private void coursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesButtonActionPerformed
        // TODO add your handling code here:
            dispose();
            new StudentCourses().setVisible(true);
    }//GEN-LAST:event_coursesButtonActionPerformed

    private void drop_classesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drop_classesMouseClicked
        // TODO add your handling code here:
        dispose();
        new StaffCourses().setVisible(true);
    }//GEN-LAST:event_drop_classesMouseClicked

    private void drop_classesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drop_classesActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:        
        Operations operations = new Operations();
    
        try{
            int userID = LoginSession.UID;
            int courseID = Integer.parseInt(courseID_txt.getText());
            int examOne = Integer.parseInt(examOne_txt.getText());
            int examTwo = Integer.parseInt(examTwo_txt.getText());
            int final_exam = Integer.parseInt(final_txt.getText());
            
            
            if(operations.dropClass(userID, courseID, examOne, examTwo, final_exam, this)){
                 JOptionPane.showMessageDialog(this, "You've succesfully dropped a class");
                 UpdateDB();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please type corret information");
        }
    }//GEN-LAST:event_drop_classesActionPerformed

    private void backToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToActionPerformed
        // TODO add your handling code here:
        dispose();
        new StaffChoices().setVisible(true);
    }//GEN-LAST:event_backToActionPerformed

    private void studentAge_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAge_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentAge_txtActionPerformed

    private void examOne_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examOne_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examOne_txtActionPerformed

    private void final_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_final_txtActionPerformed

    private void catalog_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalog_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catalog_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backTo;
    private javax.swing.JButton catalog_Button;
    private javax.swing.JTextField courseID_txt;
    private javax.swing.JTextField courseName_txt;
    private javax.swing.JButton coursesButton;
    private javax.swing.JButton drop_classes;
    private javax.swing.JTextField examOne_txt;
    private javax.swing.JTextField examTwo_txt;
    private javax.swing.JButton exit_button;
    private javax.swing.JTextField final_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField studentAge_txt;
    private javax.swing.JTextField studentLevel_txt;
    private javax.swing.JTextField studentMajor_txt;
    private javax.swing.JTextField studentName_txt;
    // End of variables declaration//GEN-END:variables
}
